#!/usr/bin/env bash

# Run this file with virtualenvwrapper's `postactivate' hook.

_session=${VIRTUAL_ENV##*/}

tmux selectp -t 0
tmux splitw -h -p 50
tmux selectp -t 1
tmux splitw -v -p 25
tmux selectp -t 0
